import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/ui/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <footer role="contentinfo" className="pt-6 pb-8 text-center text-sm border-t">
          <div className="mx-auto max-w-4xl px-4">
            <p>© {new Date().getFullYear()} Hotel Reservation System. All rights reserved.</p>
            <p className="mt-2">
              <a href="/privacy" className="underline hover:text-foreground">Privacy</a>
              <span className="mx-2">·</span>
              <a href="/terms" className="underline hover:text-foreground">Terms</a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
