spring:
    application:
      name: hotel-service
    datasource:
      url: jdbc:postgresql://localhost:5432/hoteldb
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2dll.auto: validate
          format_sql: true
          show-sql: true
          highlight_sql: true
      
server:
    port: 8081