spring:
    application:
      name: hotel-service
    datasource:
      url: jdbc:postgresql://localhost:5432/hoteldb
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
    port: 8081